# -*- coding: utf-8 -*-
"""Binomial distribution.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zaiSuoAbxfMRHyOyBOmSJFeHQFNexLFf
"""

import matplotlib.pyplot as plt
from scipy.stats import binom
import numpy as np
n=20
p=0.4
k=8
prob=binom.pmf(k,n,p)
prob=binom.pmf(k,n,p)#shows highest possibilty is 0.04  which means 60% chance for sucess
print(prob)

x = np.arange(0, n + 1)
pmf_values = binom.pmf(x, n, p)
plt.bar(x, pmf_values, color="lightblue", edgecolor="black", label="Binomial PMF")

# highlight k = 8
plt.bar(k, prob, color="orange", edgecolor="black", label=f"k = {k}")

plt.xlabel("Number of successes")
plt.ylabel("Probability")
plt.title(f" E_commerce Customer Purchase-Binomial distribution")
plt.legend()
plt.grid(axis="y", alpha=0.3)
plt.show()

from scipy.stats import binom
n=20
p=0.4
k=8
p=binom.cdf(k,n,p)
print(p)