# -*- coding: utf-8 -*-
"""kurtosis1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fgKz1OFtYnvOdhUTK4YdopZdCTBxv3xU
"""

import pandas as pd
df=pd.read_csv("sales_data.csv")
df

x=df["Sales_Amount"]
plt.hist(x, color="pink", edgecolor="black")
plt.title("Amount")
plt.xlabel("data")
plt.ylabel("list")
plt.show()

import numpy as np
from scipy.stats import kurtosis as k
x=([100,120,150,200,4,1,2,5,3,2,6,5,4,3,3,1,2])
kurto=k(profits,fisher=True)
kurto1=k(profits,fisher=False)
mean_value=np.mean(x)
max_value=max(x)
min_value=min(x)
if(kurto>0):
    print("heavy tail more distribution")
    if(max_value-mean_value)>(mean_value-min_value):
        print("big profits")
    else:
        print("big loss")
elif(kurto<0):
    print("low tail less distribution and low profit/loss")
else:
    print("normal distribution and normal profit/loss")

plt.plot(profits, color="pink")
plt.title("sales_amount")
plt.xlabel("x")
plt.ylabel("x")
plt.axhline(mean_val, linestyle="--", linewidth=3)
plt.axhline(median_val, linestyle="dotted", linewidth=2)
plt.show()