# -*- coding: utf-8 -*-
"""kurtosis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18PeGtgOQ11Fhyo9Sl_FnrIlARwZ9jdI2
"""

import numpy as np
from scipy.stats import kurtosis as k
profits=([100,120,150,200,4,1,2,5,3,2,6,5,4,3,3,1,2])
kurto=k(profits,fisher=True)
kurto1=k(profits,fisher=False)
mean_value=np.mean(profits)
max_value=max(profits)
min_value=min(profits)
if(kurto>0):
    print("heavy tail more distribution")
    if(max_value-mean_value)>(mean_value-min_value):
        print("big profits")
    else:
        print("big loss")
elif(kurto<0):
    print("low tail less distribution and low profit/loss")
else:
    print("normal distribution and normal profit/loss")

import matplotlib.pyplot as plt
plt.hist(profits, color="red", edgecolor="black")
plt.title("Profit or Loss Distribution")
plt.xlabel("Profit Values")
plt.ylabel("Frequency")
plt.show()

mean_val=np.mean(profits)
median_val=np.median(profits)
mean_val

plt.plot(profits, color="blue")
plt.title("Profit or Loss Distribution")
plt.xlabel("Profit Values")
plt.ylabel("Frequency")
plt.axhline(mean_val, linestyle="--", linewidth=3)
plt.axhline(median_val, linestyle="dotted", linewidth=2)
plt.show()

import numpy as np
from scipy.stats import kurtosis as k

# Platykurtic data (values spread out evenly)
sales = [10, 12, 15, 18, 20, 23, 25, 27, 30]

kurto = k(sales, fisher=True)

print("Kurtosis Value =", kurto)

if kurto < 0:
    print("Platykurtic → Light tail, low variation")
else:
    print("Not Platykurtic")

import numpy as np
from scipy.stats import kurtosis as k

# Mesokurtic data (normal distribution-like)
heights = [10, 12, 14, 15, 16, 15, 14, 12, 10]
kurto = k(heights, fisher=True)

print("Kurtosis Value =", kurto)

# Since perfect 0 is rare, we check "close to zero"
if kurto < 0.1:
    print("Mesokurtic → Normal distribution")
else:
    print("Not Mesokurtic")