# -*- coding: utf-8 -*-
"""Linear.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hTuhrYk9aG0jlTTkk2EPqmrQTSZTufd-
"""

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score

data=pd.read_csv("data.csv")
data

data.isnull().sum()

data.dropna(inplace=True)

data.drop_duplicates(inplace=True)

data.describe()

data.info()

x=data[['CRIM']]
x

y=data['NOX']
y

x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

model=LinearRegression()
model.fit(x_train,y_train)

y_pred=model.predict(x_test)
accuracy=r2_score(y_test,y_pred)
print(accuracy*100)

run_time=int(input("seles:"))
inputs=[[run_time]]
print("CHAS:",model.predict(inputs))

import matplotlib.pyplot as plt
plt.scatter(x,y,color="red",label="data")
plt.plot(x_test,y_pred,color="blue",label="model")
plt.title("RM")
plt.xlabel("TAX")
plt.ylabel("DIS")
plt.legend()
plt.show()