# -*- coding: utf-8 -*-
"""Matplotib.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1e6INfOZohgAB4ann2RVA5DNBa9DF7I96
"""

import pandas as pd
data=pd.read_csv("results.csv")
data

m1=data.loc[0:5,"Science"]
m2=data.loc[0:5,"History"]

science=data[["Science"]]
science

from sklearn.preprocessing import StandardScaler

i=StandardScaler()
dd=i.fit_transform(science)

import matplotlib.pyplot as plt
plt.plot(m1,m2,color="orange",marker="o")
plt.title("marks")
plt.xlabel("science")
plt.ylabel("History")
plt.show()

import numpy as np
plt.hist(m1,color="pink",bins=10,edgecolor="black")
plt.title("marks")
plt.xlabel("science")
plt.ylabel("History")
plt.show()

companies = ['Apple', 'Samsung', 'Xiaomi', 'Others']
market_share = np.array([30, 25, 20, 25])
plt.pie(market_share, labels=companies, autopct='%1.2f%%', startangle=90)
plt.title('Mobile market share')
plt.show()

days = ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun']
times = ['Morning', 'Afternoon', 'Evening']

temps = np.array([
    [28, 36, 31],
    [27, 35, 30],
    [29, 37, 32],
    [28, 38, 33],
    [30, 39, 34],
    [31, 40, 35],
    [29, 37, 33]
])

# Create the heatmap
plt.imshow(temps, cmap='OrRd', aspect='auto')# for equql cell
plt.colorbar(label="Temperature (°C)")
plt.title("Erode heat rate")

import matplotlib.pyplot as plt
import numpy as np

# Simulated monthly rainfall data (in cm)
chennai = [32, 45, 50, 60, 55, 70, 65, 80, 75, 68, 58, 50]
mumbai = [25, 40, 55, 90, 110, 120, 130, 125, 100, 70, 50, 35]
delhi = [10, 15, 25, 35, 50, 60, 65, 55, 40, 30, 20, 15]

# Create a box plot
plt.boxplot([chennai, mumbai, delhi], labels=['Chennai', 'Mumbai', 'Delhi'])
plt.show()