# -*- coding: utf-8 -*-
"""multilinear.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RjOnZGU27Z0Sk5NGJ6u_PRbpgDP6LqLT
"""

import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.metrics import  r2_score
from sklearn.model_selection import train_test_split

data=pd.read_csv("Household energy bill data.csv")
data

x2=data.fillna(data['num_rooms'].mean())
x2

x=data.loc[1:20,'housearea']
x1=x.fillna(x.mean())
x1

x2=data.loc[1:20,'amount_paid']
x2

X=np.column_stack((x1,x2))
X

y=data.loc[1:20,'ave_monthly_income']
y=y.fillna(y.mean())
y=np.array(y).reshape(-1,1)
y

model=LinearRegression()
model.fit(X,y)

housearea=float(input("Enter your housearea:"))
amount_paid=float(input("Enter your amount_paid:"))
inputss=np.column_stack((housearea,amount_paid))
print(model.predict(inputss))

x_test=X
y_test=y
y_pred=model.predict(x_test)
accuracy=r2_score(y_test,y_pred)
print(accuracy*100)

import matplotlib.pyplot as plt
fig=plt.figure()
ax=fig.add_subplot(121,projection='3d')
ax.scatter(data.loc[:,'housearea'],data.loc[:,'amount_paid'],data.loc[:,'ave_monthly_income'])
plt.title("housearea vs amount_paid vs ave_monthly_income")
ax.set_xlabel('housearea')
ax.set_ylabel('amount_paid')
ax.set_zlabel('ave_monthly_income')
plt.show()