# -*- coding: utf-8 -*-
"""qqplots.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cpJSRWhi3gVcrq9tbQe91pJ-AQlqw1D1
"""

import pandas as pd
import matplotlib.pyplot as plt
import scipy.stats as stats

df = pd.read_csv("Student_Marks.csv")

stats.probplot(
    df["time_study"],
    dist="norm",
    plot=plt
)

plt.title("normal  distribution QQ Plot - time_study")
plt.show()

df=pd.read_csv("Student_Marks.csv")
df

import pandas as pd
import matplotlib.pyplot as plt
import scipy.stats as stats

df = pd.read_csv("Mall_Customers.csv")

stats.probplot(
    df["Age"],
    dist="norm",
    plot=plt
)

plt.title("QQ Plot - Customer Age")
plt.show()

import pandas as pd
import matplotlib.pyplot as plt
import scipy.stats as stats

df = pd.read_csv("Housing-selected-columns.csv")

stats.probplot(
    df["price"],
    dist="norm",
    plot=plt
)

plt.title("Exponential distribution QQ Plot - Area")