# -*- coding: utf-8 -*-
"""regex.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GtFv9BCpCIuuwkeN8W2kPXRXyWV5KSZm
"""

import re
text="this is my email kavi@gmail.com and gowtham@gmail.com"
a=re.findall(r'\w{2,}=@\w{@,}\.\w{2,}',text)
a

['kavi@gmail.com','gowtham@gmail.com']

text=input("Enter your text")
a=re.findall(r'kavi@',text)
if a:
  print("found")
else:
   print("not found")
   a

['abc@']

txt="many students define paragraphs in terms of length: a paragraph is a group of at leats five sentences,a paragraph is half a page long,etc.In reality,though,the unity and coherncer of ideas among sentences is what constitutes a paragraph."
search=re.search(r'terms',txt)
print(search)

txt="My phone number is 3"
extract=re.search(r'\d',txt)
print(extract)

txt="my USA amount is $250"
s=re.sub(r'USA'," ",txt)
s

txt="kavi@gmail.com gowtham@gamilcom"
d=re.match(r'\w{2,}@\w{2,}\.\w{2,}',txt)
d