# -*- coding: utf-8 -*-
"""Skew.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cflOTUGxVpgawrCtJzF61jNr3cGurkNh
"""

import numpy as np
import pandas as pd
c=pd.read_csv("Employee.csv")
c

data=c["Age"]
data

from scipy.stats import skew
ans=skew(data)
if ans>0:
    print("positive skew")
elif ans<0:
    print("negative skew")
else:
    print("normal skew")

import matplotlib.pyplot as plt
plt.figure(figsize=(8,5))
plt.hist(data, color='skyblue', bins=10)
plt.title("joiningyear")
plt.xlabel("age")
plt.ylabel("gender")
plt.grid(True)
plt.show()

import numpy as np
Age=[65,72,83,94,75,1,2,3]
data=np.array(Age)
data

from scipy.stats import skew
ans=skew(data)
if ans>0:
    print("positive skew")
elif ans<0:
    print("negative skew")
else:
    print("normal skew")

import matplotlib.pyplot as plt
plt.hist(data,color="red",bins=16)
plt.title("negative skew")
plt.xlabel("Age")
plt.grid()
plt.show()