# -*- coding: utf-8 -*-
"""Task1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17KtcOBaq2BnO4lSx7aLWBuo44T98bayD
"""

import numpy as np

a = np.arange(1, 101)

print(a.ndim)
print(a.shape)
print(a.size)
print(a.dtype)
print(a.itemsize)
print(a.nbytes)

import numpy as np

a = np.array([10.5, 20.5, 30.5])

print(a.astype(np.float32).dtype)
print(a.astype(np.float64).dtype)
print(a.astype(np.int32).dtype)

import numpy as np

customers = np.array([
    [1, 25, 5000, 2, 10],
    [2, 30, 6000, 3, 15],
    [3, 22, 4500, 1, 8],
    [4, 28, 7000, 4, 20],
    [5, 35, 8000, 5, 25],
    [6, 26, 5500, 2, 12],
    [7, 32, 7500, 3, 18],
    [8, 29, 6500, 2, 14]
])

print(customers.shape)
print(customers.dtype)

import numpy as np

values = np.linspace(0, 1, 100)

print(values)
print(len(values))

a = np.arange(1,37).reshape(6,6)

np.diag(a)
np.diag(np.fliplr(a))
a[0,:]
a[2:4,2:4]
a[::2]

a = np.arange(1,49).reshape(2,4,6)

a[0]
a[:,0,:]

a = np.arange(1,13).reshape(4,3)

a.T

a.flatten()
a.ravel()

salary = np.array([20000,30000,40000,50000,60000])

(salary-salary.min())/(salary.max()-salary.min())

a = np.arange(1,41).reshape(10,4)

(a-a.mean(axis=0))/a.std(axis=0)

a = np.arange(1,41).reshape(10,4)

a-a.mean(axis=0)

# Commented out IPython magic to ensure Python compatibility.
a = np.arange(1,11)

# %timeit [x*2 for x in a]
# %timeit a*2

a = np.arange(1,21)

mean = a.mean()
std = a.std()

a[(a < mean-2*std) | (a > mean+2*std)]

a = np.array([-10,50,120,80,-5])

np.where(a < 0, 0, np.where(a > 100, 100, a))

a = np.arange(1,101)

a.mean()
np.median(a)
a.min()
a.max()
a.var()
a.std()
np.percentile(a,[25,50,75])
np.percentile(a,75)-np.percentile(a,25)

a = np.arange(1,51).reshape(10,5)

a.mean(axis=1)
a.mean(axis=0)

np.median(a,axis=1)
np.median(a,axis=0)

a.min(axis=1)
a.min(axis=0)

a.max(axis=1)
a.max(axis=0)

a = np.array([[10,20,np.nan],
              [30,np.nan,40],
              [50,60,70]])

np.isnan(a).sum(axis=0)

np.nanmean(a,axis=0)
np.nanmedian(a,axis=0)
np.nanmin(a,axis=0)
np.nanmax(a,axis=0)

a = np.array([[10,20,np.nan],
              [30,np.nan,40],
              [50,60,70]])

mean = np.nanmean(a,axis=0)

a[np.isnan(a)] = np.take(mean,np.where(np.isnan(a))[1])

a

a = np.array([10,20,np.inf,40,-np.inf,60])

np.isinf(a)
a[np.isinf(a)] = np.nan

np.nanmean(a)